{{- if eq .Values.PAAS_PLATFORM "KUBERNETES" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
  annotations:
    haproxy.router.openshift.io/timeout: 10h
spec:
  rules:
  - host: '{{ include "env.host" . }}'
    http:
      paths:
      - path: /
        pathType: "Prefix"
        backend:
          service:
            name: '{{ .Values.SERVICE_NAME }}'
            port:
              number: 8080
{{- end }}
