{{- if eq .Values.PAAS_PLATFORM "OPENSHIFT" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
  annotations:
    haproxy.router.openshift.io/timeout: 10h
spec:
  host: '{{ include "env.host" . }}'
  port:
    targetPort: web
  to:
    kind: Service
    name: '{{ .Values.SERVICE_NAME }}'
    weight: 100
status:
  ingress:
  - conditions:
    host: '{{ include "env.host" . }}'
{{- end }}
