---
kind: Service
apiVersion: v1
metadata:
    name: '{{ .Values.SERVICE_NAME }}'
spec:
  ports:
  - port: 8080
    name: web
  - port: 8090
    name: actuator
  - port: 10002
    name: ffmq
  selector:
    name: '{{ .Values.SERVICE_NAME }}'
  type: NodePort
