openapi: 3.0.1
info:
  title: ITF Reporting API
  description: ITF Reporting API
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
tags:
  - name: context-controller
    description: Context Controller
paths:
  '/context/getProperties':
    get:
      tags:
        - context-controller
      summary: getContextProperties
      operationId: getContextProperties
      parameters:
        - name: contextId
          in: query
          description: contextId
          required: true
          schema:
            type: string
            format: string
        - name: projectUuid
          in: query
          description: projectUuid
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/context/getContextVariables':
    get:
      tags:
        - context-controller
      summary: getContextVariables
      operationId: getContextVariables
      parameters:
        - name: contextId
          in: query
          description: contextId
          required: true
          schema:
            type: string
            format: string
        - name: projectUuid
          in: query
          description: projectUuid
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/context/getKeys':
    get:
      tags:
        - context-controller
      summary: getKeys
      operationId: getKeys
      parameters:
        - name: contextId
          in: query
          description: contextId
          required: true
          schema:
            type: string
            format: string
        - name: projectUuid
          in: query
          description: projectUuid
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

  '/partition/current':
    get:
      tags:
        - context-controller
      summary: getCurrentPartitionNumbers
      operationId: getCurrentPartitionNumbers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
